name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          cd slides
          npm ci --production
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: slides/dist
